### ISSUE TITLE
Release 1.0.0 - Milestone

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/doc-library#5]
For the release, the below tasks must be completed:

- [ ] Review from 2nd Person
- [ ] Approval from wtd community
- [ ] All related issues must be fixed
